version: '3.8'

services:
  postgres:
    command: postgres -c max_connections=200 -c shared_buffers=1GB
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d  # Монтируем скрипты инициализации
    ports:
      - "5432:5432"
    networks:
      - bot_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - bot_network

networks:
  bot_network:

volumes:
  postgres_data:
